export default function TermsConditions() {
    return (
    <>
    <div className="w-screen min-h-screen flex justify-center bg-[#f3f9fb] pt-11 pb-36">
            <div className="bg-white w-full max-w-4xl h-auto p-8 rounded-lg shadow-lg border mt-10 mx-4 sm:mx-10 mb-10 pt-20 border-gray-300">
                <h1 className="font-thin text-3xl mb-6 text-[#000000]">Terms & Conditions</h1>
                <p className="text-l mb-6 text-justify text-gray-700">Effective Date: 29-10-2024</p>
                <p className="text-l mb-6 text-justify text-gray-700">Welcome to Trading with Jarit. By accessing our website (tradingwithjarit.in) and purchasing or using any of the informational software we provide, you agree to comply with and be bound by the following terms and conditions. Please read them carefully. If you do not agree with these terms, please refrain from using our services.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">1. Scope of Service:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">Trading with Jarit offers software solutions for informational purposes only. These tools are designed to help users gain insights and analyze various trading-related data. Trading with Jarit does not provide financial advice, nor does it make any guarantee of accuracy or predictability of outcomes based on the software’s analysis.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">2. Disclaimer of Accuracy:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">While we strive to provide valuable and informative data through our software, Trading with Jarit does not guarantee 100% accuracy in its predictions or analyses. Market trends, data sources, and other variables can affect the accuracy of information provided. Users acknowledge that all data, predictions, and other insights generated by our software are for reference only and should not be solely relied upon for making financial decisions.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">3. Limitation of Liability:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">Trading with Jarit shall not be liable for any loss, damage, or financial loss incurred as a result of using our software, including but not limited to direct, indirect, incidental, or consequential damages. The user agrees to assume full responsibility for any trading or financial decisions made using information provided by our software. Trading with Jarit is not responsible for any outcomes of such decisions.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">4. User Responsibility:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">Users are responsible for understanding the nature of informational software and the inherent risks of relying on analytical tools for trading decisions. Users agree to use the software for informational purposes only and are advised to consult a professional financial advisor for personalized financial guidance.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">5. Refunds Policy:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">Returns are accepted only within three (3) calendar days from the date of purchase. Customers must provide a valid reason for the return along with proof of purchase, such as an invoice or receipt. Please refer to refund policy for complete details.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">6. Intellectual Property:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">All software, content, and materials provided by Trading with Jarit are the intellectual property of Trading with Jarit. Users may not copy, distribute, or modify the software or any other proprietary material provided without explicit permission.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">7. Indemnification:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">By using Trading with Jarit’s software, users agree to indemnify and hold harmless Trading with Jarit, its employees, and affiliates from any claims, damages, or losses arising from or related to their use of the software or violation of these terms.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">8. Changes to Terms and Conditions:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">Trading with Jarit reserves the right to modify or update these Terms and Conditions at any time without prior notice. Users are encouraged to review this page periodically for any changes. Continued use of our services following changes implies acceptance of those changes.</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">9. Governing Law and Jurisdiction:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">These Terms and Conditions are governed by and construed in accordance with the laws of [Your Jurisdiction]. Any disputes arising from or related to these terms or the use of our software will be resolved in the courts of [Your Jurisdiction].</p>

                <h2 className="font-thin text-2xl mt-8 mb-6 text-black">10. Contact Information:</h2>
                <p className="text-l mb-6 text-justify text-gray-700">For any questions, concerns, or grievances, please contact us at:</p>
                <p className="text-l mb-6 text-justify text-gray-700">Email: tradingwithjarit@gmail.com</p>
                <p className="text-l mb-6 text-justify text-gray-700">Telegram: <a href="https://telegram.me/jaritmunjal12" className="text-blue-500">https://telegram.me/jaritmunjal12</a></p>
                <p className="text-l mt-4 text-justify text-black">By purchasing and using the software provided by Trading with Jarit, you acknowledge that you have read, understood, and agree to abide by these Terms and Conditions.</p>
            </div>
        </div>


    
    
    
    </>
    );
}